The-Tuan
GiaoLe/apartment-management pull request #3
Opened 2023-10-26 04:03 UTC by TheTuanub244

2023-10-26 07:36 UTC, GiaoLe requested changes
Please get back to me as soon as possible. Have a nice day.

2023-10-26 07:36 UTC, GiaoLe commented on src/main/java/com/example/demo/controller/ApartmentFormController.java
The room counting part was confused me since I don't see its serve anything to the program, and you only printing it out for testing purpose? Imo, the testing part can be written in test folder. Also don't comment out the code, it's a good practice that you choose the working version.

2023-10-26 07:36 UTC, GiaoLe commented on src/main/java/com/example/demo/controller/MenuController.java
I've moved the TableView of apartment from MenuController to ApartmentListController and I don't see any reason for recreating it here. And you are using wildcards(?) for generics in TableColumn, imo it's bad because you can't use TableColumn.setCellValueFactory to add value to columns properly.

2023-10-26 07:36 UTC, GiaoLe commented on src/main/java/com/example/demo/dao/Apartment.java
You deleted the code for counting residents in an apartment. Please fix this.

2023-10-26 07:36 UTC, GiaoLe commented on src/main/resources/images/home.png
Nice login form.

2023-10-29 14:36 UTC, TheTuanub244 commented on src/main/java/com/example/demo/controller/ApartmentFormController.java
i think the room couting part helps the admin know the status about the room of that floor so that we can  update the information about the apartment

2023-10-31 07:27 UTC, closed without merging

2023-10-31 07:27 UTC, GiaoLe commented
New branch was created and this was outdated